. Support Vector Machine or SVM is one of the most popular Supervised Learning algorithms,which is used for Classification as well as Regression problems.However,primarily,it is used for Classification problems in Machine learning.

. The goal of the SVM algorithm is to create the best line or decision boundary that can segregate n-dimensional space into classes so that we can easily put the new data point in the corect category in the future. This decision boundary is called a hyperplane.

. SVM chooses the extreme points/vectors that help in creating the hyperplane.These extremes cases are called as support vectors,and support vectors,and hence algorithm is termed as Support Vector Machine.

Types of SVM:-

SVM can be two types:-

Linear SVM:- Linear SVM is used for linearly separable data,which means if a dataset can be classified into two classes by using a single straight line,then such data is termed as linearly separable data,and classifier is used called as Linear SVM classifier.

Non-linear SVM:- Non-Linear SVM is used for non-linearly separated data,which means if a dataset cannot be classified by using a straight line, then such data is termed as non-linear data and classifier used is called as Non-linear SVM classifier.



In [1]:
# import Essential Libraries
import numpy as np
import pandas as pd

In [2]:
# Read the dataset
df = pd.read_csv("dtsvm.csv")
df.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [3]:
df.shape

(400, 5)

In [4]:
# check missing values
df.isnull().sum()

User ID            0
Gender             0
Age                2
EstimatedSalary    2
Purchased          0
dtype: int64

In [5]:
# separate dataset into independent and dependent variables
X = df.iloc[:,[2,3]].values
X

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01,      nan],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [6]:
Y = df.iloc[:,4].values
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [7]:
# handle missing values
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan, strategy='mean')
X=si.fit_transform(X)
X

array([[1.90000000e+01, 1.90000000e+04],
       [3.50000000e+01, 2.00000000e+04],
       [2.60000000e+01, 4.30000000e+04],
       [2.70000000e+01, 5.70000000e+04],
       [1.90000000e+01, 7.60000000e+04],
       [2.70000000e+01, 5.80000000e+04],
       [2.70000000e+01, 8.40000000e+04],
       [3.20000000e+01, 1.50000000e+05],
       [2.50000000e+01, 3.30000000e+04],
       [3.50000000e+01, 6.50000000e+04],
       [2.60000000e+01, 8.00000000e+04],
       [2.60000000e+01, 5.20000000e+04],
       [2.00000000e+01, 8.60000000e+04],
       [3.20000000e+01, 1.80000000e+04],
       [1.80000000e+01, 8.20000000e+04],
       [2.90000000e+01, 8.00000000e+04],
       [4.70000000e+01, 2.50000000e+04],
       [4.50000000e+01, 2.60000000e+04],
       [4.60000000e+01, 2.80000000e+04],
       [4.80000000e+01, 2.90000000e+04],
       [4.50000000e+01, 2.20000000e+04],
       [4.70000000e+01, 4.90000000e+04],
       [4.80000000e+01, 4.10000000e+04],
       [4.50000000e+01, 2.20000000e+04],
       [4.600000

In [8]:
# splitting the dataset in Train Test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [9]:
X_test.shape

(80, 2)

In [10]:
# for normalization data using Feature Scaling
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

In [11]:
# Apply SVM Algorithm
from sklearn.svm import SVC
model= SVC(kernel='linear',random_state=0)
model.fit(X_train,Y_train)

SVC(kernel='linear', random_state=0)

In [12]:
# Test the model 
y_pred =model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [13]:
Y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [14]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,y_pred)
cm

array([[52,  6],
       [ 3, 19]])

71 match 
71*100/80 = 88%

In [15]:
import pickle

In [16]:
pickle.dump(model,open('svm.pkl','wb'))